/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class simon_fractal_rendering_cpp_CppRenderHandle */

#ifndef _Included_simon_fractal_rendering_cpp_CppRenderHandle
#define _Included_simon_fractal_rendering_cpp_CppRenderHandle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     simon_fractal_rendering_cpp_CppRenderHandle
 * Method:    create
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_simon_fractal_rendering_cpp_CppRenderHandle_create
  (JNIEnv *, jclass, jint);

/*
 * Class:     simon_fractal_rendering_cpp_CppRenderHandle
 * Method:    renderNative
 * Signature: (J[ILjava/lang/String;Ljava/lang/String;IDDDDII[D[D[I)V
 */
JNIEXPORT void JNICALL Java_simon_fractal_rendering_cpp_CppRenderHandle_renderNative
  (JNIEnv *, jclass, jlong, jintArray, jstring, jstring, jint, jdouble, jdouble, jdouble, jdouble, jint, jint, jdoubleArray, jdoubleArray, jintArray);

/*
 * Class:     simon_fractal_rendering_cpp_CppRenderHandle
 * Method:    cancelNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_simon_fractal_rendering_cpp_CppRenderHandle_cancelNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     simon_fractal_rendering_cpp_CppRenderHandle
 * Method:    closeNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_simon_fractal_rendering_cpp_CppRenderHandle_closeNative
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
